### ISSUE TITLE
import _C.nms causes undefined symbol error

### ISSUE THREAD

**Issue by nikisalli** [ddshan/hand_object_detector#15]
maybe some useful build flags are missing

**Comment by WillLiGitHub** [comment]
i have the same problem!!!

**Comment by WillLiGitHub** [comment]
setup falied.

**Comment by ddshan** [comment]
Have you solved the issue? Usually, it is related to building the environment. Could you try the steps carefully again?
Otherwise, could you share the details about the issue?

**Comment by nikisalli** [comment]
I followed all the steps carefully again, everything compiles but the demo fails with an undefined symbol error:
`CUDA_VISIBLE_DEVICES=0 python demo.py --cuda --checkepoch=8 --checkpoint=132028`
```Traceback (most recent call last):
  File "demo.py", line 34, in <module>
    from model.roi_layers import nms
  File "/home/nik/Desktop/progetti/hand_object_detector/lib/model/roi_layers/__init__.py", line 3, in <module>
    from .nms import nms
  File "/home/nik/Desktop/progetti/hand_object_detector/lib/model/roi_layers/nms.py", line 3, in <module>
    from model import _C
ImportError: /home/nik/Desktop/progetti/hand_object_detector/lib/model/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv

**Comment by ddshan** [comment]
Can you take a look and try this fix (https://github.com/jwyang/faster-rcnn.pytorch/issues/503) from [faster-rcnn.pytorch](https://github.com/jwyang/faster-rcnn.pytorch) and see if it works?

**Comment by nikisalli** [comment]
I tried many versions of torch (1.0.0, 1.0.1, 1.3.0) and rebuilt what's under lib many times but I couldn't manage to solve the environment's issues. The best scenario I got was a numpy import error but it wasn't solveable due to many dependency conflicts and I couldn't reproduce it anyways.

**Comment by nikisalli** [comment]
this are my system's specs if it can be useful in any way
Kernel: 5.15.2-arch1-1 x86_64 bits: 64 compiler: gcc v: 11.1.0 Distro: Arch Linux
cuda 11.5.0-1
cudnn 8.2.4.15-1

**Comment by oliviaylee** [comment]
Encountering the same issue, are there any updates on how this was resolved?

**Comment by oliviaylee** [comment]
Update: [this fix](https://github.com/facebookresearch/maskrcnn-benchmark/issues/891) works for me for now. However, because it differs from the environment specifications in the ReadMe, I wouldn't be surprised if this caused errors for me further down the line, so I would not consider this resolved unless the code authors can verify that this environment setup also works for the codebase.

**Comment by huamo555** [comment]
> 更新：[此修复](https://github.com/facebookresearch/maskrcnn-benchmark/issues/891)程序目前对我有用。但是，由于它与 ReadMe 中的环境规范不同，因此如果这给我带来了后续错误，我不会感到惊讶，因此我不会认为此问题已解决，除非代码作者可以验证此环境设置也适用于代码库。

您解决了这个问题吗？

**Comment by misaelrezende** [comment]
Contributing with my two cents...

I had a similar issue, but in my case I could not import this line `from model import _C`. Also, I was not able to run `python setup.py build develop` that as author says "Compile the cuda dependencies..."
My computer has cuda 12.4 and the suggested pytorch version requires cuda 11.3.


I was able to solve this problem without having to install cuda 11.3 and run `python demo.py` by installing pytorch 2.1, with this command:
`conda install pytorch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 pytorch-cuda=12.1 -c pytorch -c nvidia`

Then, finally, I could compile the dependencies with `python setup.py build develop` and later run the demo application.
