### ISSUE TITLE
Cannot run demo

### ISSUE THREAD

**Issue by hongsukchoi** [ddshan/hand_object_detector#20]
Hi, great work!

I can't run the demo. 
Whenever I run the demo, I get this error while loading the checkpoint weights to the network.
```
*** RuntimeError: CUDA error: unknown error
```

If I try to load the weights in the python interactive mode, I have no problem.
Some dependencies related to these imports seem to cause the trouble, but not sure. 
```
from model.roi_layers import nms
from model.faster_rcnn.vgg16 import vgg16
from model.faster_rcnn.resnet import resnet
```

Please help me.

**Comment by hongsukchoi** [comment]
This is the full error message
```
Traceback (most recent call last):
  File "demo.py", line 193, in <module>
    checkpoint = torch.load(load_name)
  File "/home/hongsuk.c/anaconda3/envs/handobj/lib/python3.6/site-packages/torch/serialization.py", line 368, in load
    return _load(f, map_location, pickle_module)
  File "/home/hongsuk.c/anaconda3/envs/handobj/lib/python3.6/site-packages/torch/serialization.py", line 542, in _load
    result = unpickler.load()
  File "/home/hongsuk.c/anaconda3/envs/handobj/lib/python3.6/site-packages/torch/serialization.py", line 505, in persistent_load
    data_type(size), location)
  File "/home/hongsuk.c/anaconda3/envs/handobj/lib/python3.6/site-packages/torch/serialization.py", line 114, in default_restore_location
    result = fn(storage, location)
  File "/home/hongsuk.c/anaconda3/envs/handobj/lib/python3.6/site-packages/torch/serialization.py", line 96, in _cuda_deserialize
    return obj.cuda(device)
  File "/home/hongsuk.c/anaconda3/envs/handobj/lib/python3.6/site-packages/torch/_utils.py", line 76, in _cuda
    return new_type(self.size()).copy_(self, non_blocking)
  File "/home/hongsuk.c/anaconda3/envs/handobj/lib/python3.6/site-packages/torch/cuda/__init__.py", line 496, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: CUDA error: unknown error

```

**Comment by hongsukchoi** [comment]
I solved myself. It was the problem of compiling faster-rcnn modules (ex. nms).
My computer had no cuda-10.0.

So I just intalled pytorch with cuda-11.3, which my computer (Ubuntu 20.04) supports.

conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
